<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'name' => 'Product 1',
                'description' => 'Detailed description for product 1',
                'short_description' => 'Short description for product 1',
                'price' => 100.0000,
                'special_price' => 90.0000,
                'special_price_type' => 1,
                'special_price_start' => '2025-01-01',
                'special_price_end' => '2025-01-31',
                'selling_price' => 90.0000,
                'sku' => 'SKU001',
                'manage_stock' => 1,
                'qty' => 100,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-01-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 2,
                'name' => 'Product 2',
                'description' => 'Detailed description for product 2',
                'short_description' => 'Short description for product 2',
                'price' => 200.0000,
                'special_price' => 180.0000,
                'special_price_type' => 1,
                'special_price_start' => '2025-02-01',
                'special_price_end' => '2025-02-28',
                'selling_price' => 180.0000,
                'sku' => 'SKU002',
                'manage_stock' => 1,
                'qty' => 200,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-02-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 3,
                'name' => 'Product 3',
                'description' => 'Detailed description for product 3',
                'short_description' => 'Short description for product 3',
                'price' => 300.0000,
                'special_price' => 270.0000,
                'special_price_type' => 2, // Percent
                'special_price_start' => '2025-03-01',
                'special_price_end' => '2025-03-31',
                'selling_price' => 270.0000,
                'sku' => 'SKU003',
                'manage_stock' => 1,
                'qty' => 150,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-03-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 4,
                'name' => 'Product 4',
                'description' => 'Detailed description for product 4',
                'short_description' => 'Short description for product 4',
                'price' => 400.0000,
                'special_price' => 340.0000,
                'special_price_type' => 2,
                'special_price_start' => '2025-04-01',
                'special_price_end' => '2025-04-30',
                'selling_price' => 340.0000,
                'sku' => 'SKU004',
                'manage_stock' => 0,
                'qty' => null,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-04-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 5,
                'name' => 'Product 5',
                'description' => 'Detailed description for product 5',
                'short_description' => 'Short description for product 5',
                'price' => 500.0000,
                'special_price' => 400.0000,
                'special_price_type' => 1,
                'special_price_start' => '2025-05-01',
                'special_price_end' => '2025-05-31',
                'selling_price' => 400.0000,
                'sku' => 'SKU005',
                'manage_stock' => 1,
                'qty' => 250,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-05-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 6,
                'name' => 'Product 6',
                'description' => 'Detailed description for product 6',
                'short_description' => 'Short description for product 6',
                'price' => 600.0000,
                'special_price' => 510.0000,
                'special_price_type' => 2,
                'special_price_start' => '2025-06-01',
                'special_price_end' => '2025-06-30',
                'selling_price' => 510.0000,
                'sku' => 'SKU006',
                'manage_stock' => 1,
                'qty' => 300,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-06-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 7,
                'name' => 'Product 7',
                'description' => 'Detailed description for product 7',
                'short_description' => 'Short description for product 7',
                'price' => 700.0000,
                'special_price' => null,
                'special_price_type' => 1,
                'special_price_start' => null,
                'special_price_end' => null,
                'selling_price' => 700.0000,
                'sku' => 'SKU007',
                'manage_stock' => 0,
                'qty' => null,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-07-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 8,
                'name' => 'Product 8',
                'description' => 'Detailed description for product 8',
                'short_description' => 'Short description for product 8',
                'price' => 800.0000,
                'special_price' => 720.0000,
                'special_price_type' => 2,
                'special_price_start' => '2025-08-01',
                'special_price_end' => '2025-08-31',
                'selling_price' => 720.0000,
                'sku' => 'SKU008',
                'manage_stock' => 1,
                'qty' => 400,
                'in_stock' => 1,
                'is_active' => 0,
                'new_from' => '2025-08-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 9,
                'name' => 'Product 9',
                'description' => 'Detailed description for product 9',
                'short_description' => 'Short description for product 9',
                'price' => 900.0000,
                'special_price' => 810.0000,
                'special_price_type' => 1,
                'special_price_start' => '2025-09-01',
                'special_price_end' => '2025-09-30',
                'selling_price' => 810.0000,
                'sku' => 'SKU009',
                'manage_stock' => 1,
                'qty' => 450,
                'in_stock' => 0,
                'is_active' => 1,
                'new_from' => '2025-09-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ],
            [
                'brand_id' => 10,
                'name' => 'Product 10',
                'description' => 'Detailed description for product 10',
                'short_description' => 'Short description for product 10',
                'price' => 1000.0000,
                'special_price' => 850.0000,
                'special_price_type' => 2,
                'special_price_start' => '2025-10-01',
                'special_price_end' => '2025-10-31',
                'selling_price' => 850.0000,
                'sku' => 'SKU010',
                'manage_stock' => 1,
                'qty' => 500,
                'in_stock' => 1,
                'is_active' => 1,
                'new_from' => '2025-10-01 00:00:00',
                'new_to' => '2025-12-31 23:59:59',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null
            ]
        ]);
    }
}
